### ISSUE TITLE
Compilation Error from the Cache Module

### ISSUE THREAD

**Issue by AyeshW** [ballerina-platform/ballerina-library#5915]
**Description:**
I have two ballerina module, one contains configurations and other one uses it. `config` module has following constants (values are not actual values).
```
public const int CAPACITY = 10;
public const float EVICTION_FACTOR = 0.2;
public const decimal DEFAULT_MAX_AGE = 30;
public const decimal CLEANUP_INTERVAL = 60;
```

Inside the other module, I use these constants to initialize the `CacheConfig`. Code segment can be found below.
```
import ballerina/cache;

final cache:CacheConfig cacheConfig = {
    capacity: config:CAPACITY,
    evictionFactor: config:EVICTION_FACTOR,
    defaultMaxAge: config:DEFAULT_MAX_AGE,
    cleanupInterval: config:CLEANUP_INTERVAL
};
```
Error Logs:
```
ERROR [foo.bal:(44:15,44:30)] invalid value: For input string: "config:CAPACITY"
ERROR [foo.bal:(45:21,45:43)] invalid value: For input string: "config:EVICTION_FACTOR"
ERROR [foo.bal:(46:20,46:42)] invalid value: For input string: "config:DEFAULT_MAX_AGE"
ERROR [foo.bal:(47:22,47:45)] invalid value: For input string: "config:CLEANUP_INTERVAL"
```

The same code was working in ballerina version 2201.0.0 without an issue.

**Steps to reproduce:**

**Affected Versions:**
2201.8.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
